[package]
name = "spotify_token_service"
version = "0.1.0"
authors = ["Michael Stock <mikeastock@gmail.com>"]

[dependencies]
chrono = "*"
hyper = "*"
iron = "*"
logger = "*"
regex = "0.1.41"
router = "*"
rustc-serialize = "0.3"
urlencoded = "*"
