[package]
name = "spotify_token_service"
version = "0.1.0"
authors = ["Michael Stock <mikeastock@gmail.com>"]

[dependencies]
iron = "*"
urlencoded = "*"
router = "*"
logger = "*"
rustc-serialize = "0.3"
regex = "0.1.41"
